# Generated by Django 3.0.8 on 2020-07-15 05:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=200, verbose_name='部品名')),
                ('part_number', models.CharField(max_length=20, unique=True, verbose_name='部品番号')),
                ('part_amount', models.FloatField(default=0, verbose_name='数量')),
                ('part_unit', models.CharField(max_length=200, verbose_name='単位')),
                ('part_place', models.CharField(max_length=200, verbose_name='保管場所')),
                ('part_supplier', models.URLField(blank=True, verbose_name='調達先')),
                ('part_remark', models.TextField(blank=True, verbose_name='備考')),
            ],
            options={
                'db_table': 'partlist',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='日付')),
                ('transaction_diff', models.FloatField(default=0, verbose_name='変更量')),
                ('transaction_remark', models.TextField(blank=True, verbose_name='備考')),
                ('transaction_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partlist.Part', verbose_name='部品名')),
                ('transaction_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
