# Generated by Django 3.0.8 on 2020-07-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_user',
        ),
    ]
